repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
    -   id: ruff
        args: [ "--output-format", "pylint" ]
    -   id: ruff-format
        args: [ --check ]
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: "mypy --strict"
        language: python
        language_version: python3.10
        additional_dependencies: ["mypy==1.14.1"]
        types: [python]
        verbose: true
